### ISSUE TITLE
Bluetooth Headset Audio Quality Fix Toggle

### ISSUE THREAD

**Issue by helldivers2fixes** [helldivers2fixes/HellbombScript#12]
- [x] Add fix for Bluetooth audio issues. #15 
- [x] Stop and Disable ``Bluetooth Audio Gateway Service`` service on startup. #15 
- [x] Ensure it's a toggle so that users can undo this action if they desire #15

**Comment by helldivers2fixes** [comment]
Resolved with #15
